DROP TABLE IF EXISTS T_BOOKMARK_CARD;
DROP TABLE IF EXISTS T_BOOKMARK_CARD_GROUP;

CREATE TABLE T_BOOKMARK_CARD (
  ID serial PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(500),
  SHORT_URL VARCHAR(1024) NOT NULL,
  ACTUAL_URL VARCHAR(1024) NOT NULL,
  FEVICON VARCHAR(100),
  EXPIRY_DATE DATE,
  CREATED_BY VARCHAR(50),
  CREATION_DATE DATE,
  MODIFIED_BY VARCHAR(50),
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_T_BOOKMARK_CARD INCREMENT 1 START 1;


CREATE TABLE T_BOOKMARK_CARD_GROUP (
  ID serial PRIMARY KEY,
  GROUP_NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(500),
  GROUP_URL VARCHAR(1024) NOT NULL,
  TEAM VARCHAR(1024) NOT NULL,
  CARDS JSONB,
  CREATED_BY VARCHAR(50),
  CREATION_DATE DATE,
  MODIFIED_BY VARCHAR(50),
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_T_BOOKMARK_CARD_GROUP INCREMENT 1 START 1;