DROP TABLE IF EXISTS T_CARD_DETAIL;

CREATE TABLE T_CARD_DETAIL (
  ID serial PRIMARY KEY,
  TITLE VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  SHORT_URL VARCHAR2(1024) NOT NULL,
  ACTUAL_URL VARCHAR2(1024) NOT NULL,
  FEVICON VARCHAR2(100),
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  MODIFIED_BY VARCHAR2(50),
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CARD_DETAIL INCREMENT 1 START 1;