DROP TABLE IF EXISTS T_CARD_BMK;
DROP TABLE IF EXISTS T_GROUP_BMK;
DROP TABLE IF EXISTS T_USER_BMK;

CREATE TABLE T_CARD_BMK (
  ID serial PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(500),
  SHORT_URL VARCHAR(1024) NOT NULL,
  LONG_URL VARCHAR(1024) NOT NULL,
  URL_TEAM_TYPE VARCHAR(100),
  FEVICON VARCHAR(100),
  EXPIRY_DATE DATE,
  APPROVED BOOLEAN NOT NULL,
  GROUP_DETAIL JSONB,
  CREATED_BY VARCHAR(50),
  CREATION_DATE DATE,
  MODIFIED_BY VARCHAR(50),
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CARD_BMK INCREMENT 1 START 1;


CREATE TABLE T_GROUP_BMK (
  ID serial PRIMARY KEY,
  GROUP_NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(500),
  GROUP_URL VARCHAR(1024) NOT NULL,
  GROUP_ADMIN JSONB NOT NULL,
  CREATED_BY VARCHAR(50),
  CREATION_DATE DATE,
  MODIFIED_BY VARCHAR(50),
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_GROUP_BMK INCREMENT 1 START 1;

CREATE TABLE T_USER_BMK (
  ID serial PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ROLE VARCHAR(15) NOT NULL,
  CREATION_DATE DATE,
  MODIFIED_DATE DATE
);

CREATE SEQUENCE IF NOT EXISTS SEQ_USER_BMK INCREMENT 1 START 1;
